### ISSUE TITLE
Stable display order for <cob-map> layers

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/patterns#249]
Currently the order that layers appear is slightly non-deterministic because the config events are not firing always in source order.

The layers should appear in the order in which they're specified as `<cob-map>` children.

**Comment by finneganh** [comment]
Adding tech debt because this is flaking out our regression tests.

**Comment by fionawhim** [comment]
Now just using the JSON config, so no need to bother with embedded HTML elements.
