### ISSUE TITLE
mobile: responsive table bug

### ISSUE THREAD

**Issue by BrutiAnteneh** [CityOfBoston/patterns#302]
#### Expected Behavior/Acceptance Criteria 
<br>

Tables should be centered on the page, and responsive when viewed on mobile phones in portrait and landscape view.

URL: https://www.boston.gov/parks-and-playgrounds

On iPhone X:

![desired outcome - screenshot_20180301-174727](https://user-images.githubusercontent.com/33470951/38574316-8b4cde02-3cc6-11e8-9e86-53272a31d57d.png)

#### Actual Behavior
<br>

on iPhone:
![south end screenshot_20180301-173933](https://user-images.githubusercontent.com/33470951/38574421-c56984a0-3cc6-11e8-8d1e-9099629f468f.png)

On Android:
![android portrait](https://user-images.githubusercontent.com/33470951/38579985-bd6bce60-3cd6-11e8-8872-29d01b5aa40d.jpg)

#### Browser
<br> 
see below

#### Device
<br> 

**Samsung Galaxy S8**
Release: 2017, April
OS: Android, v7
Browser: Chrome
Screen Size: 5.8 in - 2.5 x 5.2 in
Resolution: 1440 x 2960 px
Viewport: 360 x 740 dp
Aspect Ratio: 18.5 : 9

**IPHONE X** 
Release: 2017, September
OS: OS, v11
Browser:  Safari
Screen Size: 5.8 in - 2.79 x 5.65 in
Resolution: 1125 x 2436 px
Viewport: 375 x 812 dp
Aspect Ratio 19.5 : 9

#### Example URL
<br> 

URL: https://www.boston.gov/metrolist/lottery-and-resale
URL: https://www.boston.gov/transportation/performance-parking-pilot
URL: https://www.boston.gov/parks-and-playgrounds

#### Relevant Screenshot(s) or Logs
<br> 

Tables Discussed elsewhere: see comment from @jimafisk:
#730 Replace table formatting on websites 

#### Steps to Reproduce the Behavior/How to Test
<br> 
 
1. On your mobile phone, go to a URL that has one of these tables.
2. Expand a drawer to expose the table within.
3. Verify that the table is centered and has a border.
4. Rotate the phone and verify the table is responsive (i.e. nothing breaks, still aligned, centered, with border)
5. Repeat steps 1-5 for each drawer.

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by BrutiAnteneh** [comment]
@davidrkupton, this is mostly fixed with 2 exceptions on the Parks and Playgrounds page:

**Environment**: iphone x, Safari 11

**URL** https://www.boston.gov/parks-and-playgrounds

**Charlestown:**

![parks and playgrounds - charlestown bs_realios_mobile_iphone x-11 0](https://user-images.githubusercontent.com/33470951/43411600-a46dde02-93f8-11e8-96d8-221dce0e7183.jpg)

**Back Bay - Beacon Hill:**

![parks and playgrounds - back bay beacon hill bs_realios_mobile_iphone x-11 0](https://user-images.githubusercontent.com/33470951/43411619-b0038afa-93f8-11e8-92ff-61281b41cf60.jpg)

**Comment by BrutiAnteneh** [comment]
@davidrkupton this doesn't pass because data source for these tables is manually entered (i.e. not salesforce).

**Comment by davidrkupton** [comment]
@BrutiAnteneh : this is currently a PR on patterns.  There is no "drupal" code change required, so the fix will appear on boston.gov staging when patterns is pushed to staging.

**Comment by davidrkupton** [comment]
@BrutiAnteneh - this has been merged and is now ready to deploy to staging with the next patterns deploy.
