### ISSUE TITLE
Missing separator on "Day" filter for maps

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/patterns#357]
We're missing a separator on the "Day" filter:
![image](https://user-images.githubusercontent.com/12868231/43644388-87476558-96fc-11e8-8530-9bd6f3632771.png)

The farmer's market map is a good example ([link to drupal draft](https://edit.boston.gov/node/4721/draft#map--239791)). Also happening on food trucks ([drupal draft](https://edit.boston.gov/node/21311/draft#map--239776))

Confirmed that both have "separator" set in their configs where I think there should be one:
![image](https://user-images.githubusercontent.com/12868231/43644517-07493132-96fd-11e8-875f-fb4c76a5bf5a.png)

**Comment by fionawhim** [comment]
Try `{"type": "separator"}`

**Comment by paylakatel** [comment]
That worked - thank you!
