### ISSUE TITLE
Use blue waypoint marker when showing user's location

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/patterns#368]
Could we use [blue way point marker](https://github.com/CityOfBoston/design-team-workflow/issues/799) when showing user's current location?

**Comment by fionawhim** [comment]
<img width="975" alt="screen shot 2018-08-20 at 2 21 05 pm" src="https://user-images.githubusercontent.com/260837/44358954-762b7d00-a484-11e8-8dff-d7d5f1107a01.png">
