### ISSUE TITLE
Food trucks map filters getting stuck

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/patterns#375]
figure out if there is a bug in filtering - specifically when we pick a specific truck on [food trucks](https://www.boston.gov/departments/small-business-development/city-boston-food-trucks-schedule#map--239776) does it always change?? Feels like _sometimes_ it might not

**Comment by fionawhim** [comment]
Repro:

 - Change Day to "All"
 - Select a specific truck that clusters
 - Click on the cluster to spider it open
 - Switch to a different truck

What should happen:
 - New content should come in

What does happen:
 - UI gets stuck on that truck that's spidered open

**Comment by reillyzlab** [comment]
No one has mentioned recently so closing
