### ISSUE TITLE
Convert pattern library CSS source from Stylus to SCSS

### ISSUE THREAD

**Issue by jessicamarcus** [CityOfBoston/patterns#470]
In order to encourage contribution to Fleet, we will move from Stylus to Sass (SCSS syntax) for our CSS preprocessing.

Sass/SCSS is much more widely used; by moving in this direction, it should reduce the barrier to entry for potential collaborators.

_Jess/Phil_

**Comment by stephaniemar** [comment]
https://bostondoit.atlassian.net/browse/DIG-1105
