### ISSUE TITLE
Group of Links - Grid List

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#551]
Grid no description 
https://d8-uat.boston.gov/departments/digital-team/test-page
Hover and default states.

![image](https://user-images.githubusercontent.com/57374913/123699913-cbd82480-d82d-11eb-8932-07da05d22de4.png)

Suggested naming conventions:
Base:
gol or gp--links

Elements:
h = header
c = content
im = image
t = title
st = subtitle

Modifier:
sm = small

**Comment by subaha-cob** [comment]
Other variations
GRID WITH DESCRIPTION
<img width="1002" alt="Screen Shot 2021-06-30 at 4 58 33 PM" src="https://user-images.githubusercontent.com/57374913/124030816-8bf77580-d9c4-11eb-8671-169653455d2b.png">

**Comment by subaha-cob** [comment]
Test the following content elements using this component.

<img width="1107" alt="Screen Shot 2021-08-11 at 1 57 25 PM" src="https://user-images.githubusercontent.com/57374913/129079519-7bf7976a-5c9d-4f81-b477-82ee3a652c61.png">

**Comment by rachelsater** [comment]
@subaha-cob @padora-cob It doesn't look like the email address/phone number is the correct font

![image](https://user-images.githubusercontent.com/72876352/138896265-b65f0f81-fc88-453a-b169-6742516cf055.png)

**Comment by rachelsater** [comment]
@duffy-james this looks ok to me. what do you think?

**Comment by duffy-james** [comment]
@rachelsater The "no description" version doesn't look quite right yet. The boxes are much more narrow than the original:

![image](https://user-images.githubusercontent.com/7929556/142892731-6db10ea7-6124-42e4-a34b-7d85caf713d7.png)

Original:

![image](https://user-images.githubusercontent.com/7929556/142892778-b33b6e3d-12be-45d7-972d-7e64923310f3.png)

The version with a "description" appears to be making the text bold and all caps. There's also some extra spacing above and below the title. Here's the new version:

![image](https://user-images.githubusercontent.com/7929556/142893019-c1f8fc54-c830-43ad-926c-8390a4dd4aa0.png)

And here's the original:

![image](https://user-images.githubusercontent.com/7929556/142893097-de7f0acb-0311-43a4-ad83-e99fd84a5300.png)
