### ISSUE TITLE
GRID OF QUOTES

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#553]
https://d8-uat.boston.gov/departments/digital-team/test-page
GRID OF QUOTES

<img width="513" alt="Screen Shot 2021-06-30 at 4 53 48 PM" src="https://user-images.githubusercontent.com/57374913/124030066-d0364600-d9c3-11eb-803d-d7d4eea08c26.png">

Suggested naming conventions:
Base:
goq

Elements:
h = header
c = content
im = image
t = title
st = subtitle

Modifier:
sm = small

**Comment by subaha-cob** [comment]
@mharoc you have had this task for a while now. Where are we at with this task?

**Comment by rachelsater** [comment]
@duffy-james This looks correct to me. Can you please review it and let me know what you think?

**Comment by subaha-cob** [comment]
Also on this page @rachelsater 
https://d8-uat.boston.gov/career-center

**Comment by rachelsater** [comment]
@subaha-cob Is there meant to be a space between the " and the first/last letter?
![image](https://user-images.githubusercontent.com/72876352/138899764-b2a0d846-99fe-46af-bad4-2cbc67e7c099.png)

**Comment by subaha-cob** [comment]
Yes ;)

**Comment by rachelsater** [comment]
@subaha-cob ok thanks! @duffy-james This seems to make the design. What do you think?

**Comment by duffy-james** [comment]
@rachelsater the display looks fine -- @subaha-cob we're just focusing on the front-end with this, right?

There was an issue where users couldn't upload images to this component in the normal way, but I assumed that's separate of this work.

**Comment by rachelsater** [comment]
@subaha-cob If this ticket is just for the FE, we can move it to "ready for production"

**Comment by subaha-cob** [comment]
@rachelsater "FE" 💁🏻?

**Comment by rachelsater** [comment]
@subaha-cob sorry! Front end :)

**Comment by subaha-cob** [comment]
@rachelsater this is not just front end. I changed the markup as well.

**Comment by rachelsater** [comment]
@subaha-cob ah ok! I'll move it to "ready for production"
