### ISSUE TITLE
GROUP OF LINKS - MINI GRID

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#554]
GROUP OF LINKS - MINI GRID
https://d8-uat.boston.gov/departments/digital-team/test-page

Hover and default states.

<img width="650" alt="Screen Shot 2021-06-30 at 4 55 23 PM" src="https://user-images.githubusercontent.com/57374913/124030436-2f945600-d9c4-11eb-8448-80af327c6901.png">

Suggested naming conventions:
Base:
gol--mini

Elements:
h = header
c = content
im = image
t = title
st = subtitle

Modifier:
sm = small

**Comment by phillipbentonkelly** [comment]
This view does not match the design, its missing padding.

<img width="408" alt="Screen Shot 2021-08-06 at 11 48 49 AM" src="https://user-images.githubusercontent.com/2627273/128537262-5f1b25cd-38a2-4ab9-82b6-3eb79d824fd1.png">
<img width="706" alt="Screen Shot 2021-08-06 at 11 49 00 AM" src="https://user-images.githubusercontent.com/2627273/128537260-da6440c2-9e40-4158-9c1e-e54be0746c20.png">

Check that you're CSS is being applied and that you're using `@media-queries` if they're needed

**Comment by phillipbentonkelly** [comment]
Set the background for the icons in CSS and not in the style attribute on the tag (`<div class="lcd--mini-im"...>`)

**Comment by subaha-cob** [comment]
@carolyn-wang this is not ready for review. Fix the bug and let know.

**Comment by subaha-cob** [comment]
Hi @carolyn-wang Everything looks great here. Just one small fix with vertical alignment. Can you make the text vertically aligned. See the example I have below. The first card (Test Link - Document) is vertically aligned, but the other one is not. 

<img width="723" alt="Screen Shot 2021-08-10 at 3 02 32 PM" src="https://user-images.githubusercontent.com/57374913/128920644-6d139e4e-5feb-4db2-8976-e1a4bfb8c26c.png">

**Comment by subaha-cob** [comment]
Take a look at the examples on this page. https://stackoverflow.com/questions/8865458/how-do-i-vertically-center-text-with-css

Find a solution that doesn’t involve absolute positioning or fixed height.

**Comment by rachelsater** [comment]
@duffy-james This looks correct to me. Whatcha think?

**Comment by rachelsater** [comment]
@duffy-james this looks correct to me. whatcha think?

**Comment by rachelsater** [comment]
@duffy-james this looks correct to me. what do you think?

**Comment by duffy-james** [comment]
@rachelsater looks good to me, sorry for the delay!

**Comment by rachelsater** [comment]
no delay and thank you!
