### ISSUE TITLE
Group of links - List

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#555]
NO WITH DESCRIPTION
https://d8-uat.boston.gov/departments/digital-team/test-page
Hover and default states.

<img width="1233" alt="Screen Shot 2021-06-28 at 4 24 07 PM" src="https://user-images.githubusercontent.com/57374913/124031111-e7296800-d9c4-11eb-98e5-e0b6aa151bec.png">

Suggested naming conventions:
Base:
col-l

Elements:
h = header
c = content
im = image
t = title
st = subtitle

Modifier:
sm = small

**Comment by subaha-cob** [comment]
COL LIST - With Description

<img width="1026" alt="Screen Shot 2021-06-30 at 5 09 10 PM" src="https://user-images.githubusercontent.com/57374913/124032059-155b7780-d9c6-11eb-9fb7-84f58b311b01.png">

**Comment by subaha-cob** [comment]
Other variations - no icon

<img width="982" alt="Screen Shot 2021-06-30 at 5 11 13 PM" src="https://user-images.githubusercontent.com/57374913/124032175-3ae88100-d9c6-11eb-920b-d1c30f3507ee.png">

**Comment by subaha-cob** [comment]
@mharoc you have had this task for a while now. Where are we at with this task?

**Comment by rachelsater** [comment]
@duffy-james how does this look to you?

**Comment by duffy-james** [comment]
@rachelsater @subaha-cob 

Looks like the subheader is missing its styling in this component:

![image](https://user-images.githubusercontent.com/7929556/139909097-b99b42ca-eed6-49c9-9bf0-d73bc666c8ce.png)

I should have an "intro-text" class, I think. The hover states all look fine, though.

**Comment by rachelsater** [comment]
@subaha-cob looks good. @duffy-james what do you think?

**Comment by duffy-james** [comment]
@rachelsater looks good to me -- "Group of links - List" is good to go.

**Comment by rachelsater** [comment]
thanks!
