### ISSUE TITLE
Add cards layouts from My Neighborhood to ZeroHeight and Fleet

### ISSUE THREAD

**Issue by mmcgowanBOS** [CityOfBoston/patterns#557]
Please create Adobe XD version of the "cards" layout that is present in the My Neighborhood web app on boston.gov. @carolinestj has the original files in XD, but they may need to be updated first before migrating to ZeroHeight.

My Neighborhood web app on Boston.gov
https://www.boston.gov/my-neighborhood

Adobe XD files 
https://drive.google.com/file/d/1UJwt92Db6k1lp-Dd8pZeWfoxdWlmZfV0/view

**Comment by miyekay94** [comment]
Cards from my neighborhood have been uploaded to ZH (about 45%)
