### ISSUE TITLE
Grid of Cards - react components

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#558]
Grid of Icon cards
https://d8-uat.boston.gov/my-neighborhood?p2
Hover and default states.

<img width="825" alt="Screen Shot 2021-07-08 at 1 51 21 PM" src="https://user-images.githubusercontent.com/57374913/124968791-ee1f2e80-dff3-11eb-83ed-95bca17401c2.png">

Suggested naming conventions:
Base:
cd-i

Elements:
h = header
c = content
im = image
t = title
st = subtitle

Modifier:
sm = small

**Comment by subaha-cob** [comment]
Other card formats that needs to be added to patterns

<img width="817" alt="Screen Shot 2021-07-08 at 2 01 18 PM" src="https://user-images.githubusercontent.com/57374913/124969831-2c691d80-dff5-11eb-8f2f-b2590fb833a5.png">

**Comment by phillipbentonkelly** [comment]
@phillipbentonkelly @subaha-cob lets create a separate ticket to integrate this with the `Web App (Metrolist, etc)`
