### ISSUE TITLE
Add timeline layout to ZeroHeight and Fleet

### ISSUE THREAD

**Issue by mmcgowanBOS** [CityOfBoston/patterns#560]
Create / convert existing designs into XD and Migrate XD files to ZeroHeight. Once complete we can then add to Fleet.

Link to timeline feature / layout on Boston.gov:
https://www.boston.gov/buildinghousing/dudley-crossing

**Comment by miyekay94** [comment]
Started adding components from XD file to ZH today (about 25%); Will loop back to this once I discuss further with Megan & Caroline at today's meeting
