### ISSUE TITLE
Guides to Boston

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#565]
Guides grid of cards
https://d8-uat.boston.gov/guides
Hover and default states.

<img width="589" alt="Screen Shot 2021-07-19 at 11 02 46 AM" src="https://user-images.githubusercontent.com/57374913/126181975-1a5b2c6b-87b7-440b-abd7-8d0bd927efd5.png">

Suggested naming conventions:
Base:
ggoc

Elements:
h = header
c = content
im = image
t = title
st = subtitle

Modifier:
sm = small

**Comment by rachelsater** [comment]
@duffy-james this looks correct to me. What are your thoughts?

**Comment by duffy-james** [comment]
@rachelsater looks good to me

**Comment by rachelsater** [comment]
thanks!
