### ISSUE TITLE
Content Right - Sidebar

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#569]
Sidebar content variations
https://d8-uat.boston.gov/departments/landmarks-commission#content

<img width="382" alt="Screen Shot 2021-07-16 at 3 31 57 PM" src="https://user-images.githubusercontent.com/57374913/126194153-01da2829-47bf-43ba-aff9-4259a1a1ec87.png">

<img width="433" alt="Screen Shot 2021-07-16 at 3 50 55 PM" src="https://user-images.githubusercontent.com/57374913/126194166-21519d9b-9a2a-4a17-aa0b-1fd69de35a36.png">

<img width="379" alt="Screen Shot 2021-07-16 at 4 05 41 PM" src="https://user-images.githubusercontent.com/57374913/126194186-434a1b40-7e2d-4337-8b99-0bcdd4be0988.png">

<img width="374" alt="Screen Shot 2021-07-19 at 12 26 01 PM" src="https://user-images.githubusercontent.com/57374913/126194209-fddae58e-55cf-4659-b3a5-379e9276e115.png">

**Comment by subaha-cob** [comment]
@carolyn-wang I hope you can tackle this next. This is the next priority!

**Comment by rachelsater** [comment]
@duffy-james this looks good to me. can you please review it and let me know if there are any issues with it?

**Comment by duffy-james** [comment]
@rachelsater events sidebar looks good -- @subaha-cob can we address the extra hr rule at the bottom of the sidebar section?

![image](https://user-images.githubusercontent.com/7929556/138912632-c9839759-0115-4023-b9b1-436cb17edd26.png)

I'm guessing that would be addressed in a separate ticket, but just checking.

**Comment by subaha-cob** [comment]
@duffy-james I saw that too and I am planning on fixing it. It looks bad on the live site :)

**Comment by rachelsater** [comment]
@duffy-james it looks good to me. what do you think?

**Comment by rachelsater** [comment]
@subaha-cob looks good. moving it to ready for prod
