### ISSUE TITLE
Filters: Top or side search boxes

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#570]
https://d8-uat.boston.gov/news, https://d8-uat.boston.gov/events

<img width="365" alt="Screen Shot 2021-07-19 at 12 29 22 PM" src="https://user-images.githubusercontent.com/57374913/126194582-22330180-c698-48b3-a3f9-e4378304702a.png">

<img width="1195" alt="Screen Shot 2021-07-16 at 3 30 40 PM" src="https://user-images.githubusercontent.com/57374913/126194626-0d6c7fd2-6b05-47f1-b08a-efb2e1e8220c.png">

<img width="298" alt="Screen Shot 2021-07-16 at 3 14 48 PM" src="https://user-images.githubusercontent.com/57374913/126194682-bc9e45b4-6b36-4c92-8104-ddd1aada14f6.png">

<img width="365" alt="Screen Shot 2021-07-19 at 12 29 22 PM" src="https://user-images.githubusercontent.com/57374913/126194749-136df0b3-91b6-4b48-b040-61689a46de8d.png">

**Comment by subaha-cob** [comment]
Add the mobile version of the filters.
<img width="234" alt="Screen Shot 2021-07-19 at 2 26 23 PM" src="https://user-images.githubusercontent.com/57374913/126208824-4b583bc9-ecc2-4529-b9a3-907363e54469.png">

<img width="397" alt="Screen Shot 2021-07-19 at 2 21 54 PM" src="https://user-images.githubusercontent.com/57374913/126208842-40b45b58-5922-42ce-a83d-5ebed30e6d6e.png">


Pages with filters:
https://www.boston.gov/bid-listings
https://www.boston.gov/news
https://www.boston.gov/events
https://www.boston.gov/public-notices

**Comment by subaha-cob** [comment]
https://www.boston.gov/winter-boston

![Screen Shot 2021-07-26 at 5 00 14 PM](https://user-images.githubusercontent.com/57374913/127058601-505ee215-0572-4870-9ccf-8e7c6d93aed5.png)

**Comment by subaha-cob** [comment]
Hi @carolinestj I will be re-theming the Filters into patterns and Alex mentioned that you wanted to re-work the horizontal filters. Is it possible to do it in the next week or so? I can then incorporate it into my filters updates for boston.gov.

**Comment by carolinestj** [comment]
@subaha-cob oh I can't remember actually talking about this? haha I think you should be good for now

**Comment by rachelsater** [comment]
@duffy-james How does this look to you?

**Comment by duffy-james** [comment]
@rachelsater @subaha-cob 

For these pages, https://d8-uat.boston.gov/news, https://d8-uat.boston.gov/events

The field where you input text for a search is a default text font instead of "lora":

![image](https://user-images.githubusercontent.com/7929556/139880894-12ccc1ab-94ca-46b8-8eb7-4313f93d9bd5.png)

I think the "title" text in that section is still "monsterrat", but I would double check that.

Functionally, the search looks like it's working. I'm guessing it's not part of this ticket, but I'll just note that the items displaying on the news page appear to be broken:

![image](https://user-images.githubusercontent.com/7929556/139881582-4df9f907-0396-461b-b4e9-1b0adaad5c50.png)

![image](https://user-images.githubusercontent.com/7929556/139882004-bd67f6c5-0526-4c89-958e-1aabe8529a8d.png)

**Comment by rachelsater** [comment]
@duffy-james this looks good to me now. what do you think?

**Comment by duffy-james** [comment]
@rachelsater the "title" above each field appears to be slightly larger than the original, and bold:

![image](https://user-images.githubusercontent.com/7929556/142888979-d0173a10-85c7-49a9-8ea9-535de235087a.png)

Original:

![image](https://user-images.githubusercontent.com/7929556/142889046-6b0188ea-27dd-44cb-a639-a1a37c2573d4.png)

New:

![image](https://user-images.githubusercontent.com/7929556/142889460-50349a1a-2bfd-4e89-9820-c6a149a75db4.png)

Original:

![image](https://user-images.githubusercontent.com/7929556/142889512-407c6d47-9cfa-4e17-9c60-267895082711.png)

Also, the word "title" is appearing below the input field on both news and events. This is how the website looks now, so maybe that can get pushed off to a separate ticket?

**Comment by rachelsater** [comment]
@duffy-james Yes, a new ticket for "title" sounds like a good idea. @subaha-cob can  you please fix the "title" above each field appears to be slightly larger than the original, and bold? thanks!
