### ISSUE TITLE
Pagination update

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#572]
This is an update to an existing component.
https://d8-uat.boston.gov/public-notices

Should updated to look like this:
<img width="695" alt="Screen Shot 2021-07-16 at 3 07 12 PM" src="https://user-images.githubusercontent.com/57374913/126195782-512b26b5-4c1b-4223-a42d-35157e1f06c2.png">

**Comment by subaha-cob** [comment]
Currently looks like this:
https://patterns.boston.gov/components/detail/pagination.html
<img width="543" alt="Screen Shot 2021-07-19 at 12 41 08 PM" src="https://user-images.githubusercontent.com/57374913/126196051-e6a5f624-a6d9-4d3e-9ce0-ad112ddb496e.png">

**Comment by rachelsater** [comment]
@subaha-cob the "filter by date" font doesn't look correct. and the two buttons are touching each other. there needs to be space between them

![image](https://user-images.githubusercontent.com/72876352/138895247-53f4b8e5-e69d-4a7c-9606-291959cbed5b.png)

**Comment by rachelsater** [comment]
@subaha-cob a strange blue box is appearing if you get the "No Public Notices Found"
![image](https://user-images.githubusercontent.com/72876352/139876591-83410c23-5bd3-4f78-89c9-9a3175e239d8.png)
steps to reproduce:
1 Filter by Department > Animal Care and Control < hit Apply

also, there is no way to remove that filter and/or see all the departments again

How are the red rollovers meant to work? I'm getting red rollovers for the final 3 items in that bar
![image](https://user-images.githubusercontent.com/72876352/139877158-2999251b-007e-42ed-9e6e-9640accc8f3c.png)

**Comment by subaha-cob** [comment]
@rachelsater the pagination is correct. The filter issues should not be in this ticket. When in doubt use the current production site for comparison. I changed the color of the disabled "First" and that is fine.

**Comment by rachelsater** [comment]
@subaha-cob ok got it. @duffy-james Can you please review this and let me know your thoughts?

**Comment by rachelsater** [comment]
@duffy-james can you let me know if you think this looks correct now?

**Comment by duffy-james** [comment]
@subaha-cob @rachelsater I'm not seeing pagination at the bottom of the [public notices page](https://d8-uat.boston.gov/public-notices) on uat, but I did test that out on [the news page](https://d8-uat.boston.gov/news) and it looks fine to me.

**Comment by rachelsater** [comment]
@duffy-james @subaha-cob is this meant to appear on the public notices page?

**Comment by padora-cob** [comment]
@rachelsater @duffy-james, I think the footer is not showing on UAT because of "outdated" content / database. 

The Public Notices on UAT and CI have older DBs and are showing less then 10 (7) items because of the way we have them filter to the Archive (https://d8-uat.boston.gov/archived-public-notices) after some about of time. When a View has less then the set page number of items the pager hides automatically, we can always render it disabled with just the one page if need (personally don't recommend though). 

Seems to be working there though, I think we would be good to go :)

**Comment by rachelsater** [comment]
thanks! I'll move it into the ready for prod column
