### ISSUE TITLE
Hero: With Strikethrough text

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#579]
https://www.boston.gov/winter-boston

![Screen Shot 2021-07-26 at 3 34 12 PM](https://user-images.githubusercontent.com/57374913/127048296-287c4a6b-fc56-4a61-a655-574a14aaae3c.png)

We have a 'hero' component already. We need to add this new section to it. 
https://patterns.boston.gov/components/detail/hero--default.html

**Comment by rachelsater** [comment]
@subaha-cob @phillipbentonkelly can you please share the test link with me?

**Comment by subaha-cob** [comment]
@rachelsater 
https://d8-uat.boston.gov/buying-and-owning-home

**Comment by rachelsater** [comment]
@phillipbentonkelly @subaha-cob The image behind the text looks warped/stretched. Is that how the image looks or is there something else going on?

**Comment by subaha-cob** [comment]
@rachelsater I also noticed that this morning. That is a bug :)

**Comment by subaha-cob** [comment]
@phillipbentonkelly I have a fix for that bug already.

**Comment by rachelsater** [comment]
@duffy-james how does this look to you?

**Comment by rachelsater** [comment]
@duffy-james how does this look to you?

**Comment by duffy-james** [comment]
@rachelsater @subaha-cob what are we testing? I don't see any strikethrough text in the component.
