### ISSUE TITLE
Number Steps

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#614]
Add to Step header component

https://patterns.boston.gov/components/detail/stp--with-number.html

<img width="792" alt="Screen Shot 2021-10-08 at 9 05 08 AM" src="https://user-images.githubusercontent.com/57374913/136562443-da89aaba-5969-437b-b7b8-18731c294357.png">

**Comment by subaha-cob** [comment]
Sample page:
https://www.boston.gov/departments/public-works/how-pay-fine-code-violation

**Comment by rachelsater** [comment]
@subaha-cob can you please share the test url with me?

**Comment by subaha-cob** [comment]
@rachelsater 
https://d8-uat.boston.gov/departments/public-works/how-pay-fine-code-violation

**Comment by rachelsater** [comment]
@duffy-james this looks correct to me. can you please review it when you have time?

**Comment by duffy-james** [comment]
Couple of issues. The size of the header text in each steps is smaller than the second step here:

![image](https://user-images.githubusercontent.com/7929556/138908544-f35dda4f-3074-42c8-8a80-74ed59470a84.png)

We should keep the text size as big as it is in that second step across all of the steps on desktop. For mobile, the header images should be at the size it is in the other steps.

I checked on my phone, and the header images all looked correct in the mobile version except for that second step:

![image](https://user-images.githubusercontent.com/7929556/138910034-f56c8466-7849-4094-8112-5432bf4bd68d.png)

Looks like the "in person" text in the title of this drawer is getting pushed all the way to the right:

![image](https://user-images.githubusercontent.com/7929556/138908791-55e8bec6-ed98-4db5-9604-c2fef66d10ba.png)

**Comment by rachelsater** [comment]
@duffy-james can you please check that the issues have been fixed?

**Comment by rachelsater** [comment]
@duffy-james can you please check that the issues have been fixed?

**Comment by rachelsater** [comment]
@subaha-cob looks good! I'm moving this into ready for prod
