### ISSUE TITLE
SCHEDULE timeline UI update

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#634]
Update broken timeline. 

Should look like this:
<img width="1228" alt="Screen Shot 2021-11-05 at 8 27 11 AM" src="https://user-images.githubusercontent.com/57374913/140510135-dd73ea87-fabf-45c7-8d98-1e57a32546e8.png">

Currently looks like this:
<img width="430" alt="Screen Shot 2021-11-05 at 8 27 30 AM" src="https://user-images.githubusercontent.com/57374913/140510153-232dc0f6-bf2c-40d3-8132-ce475444ea74.png">

Page: https://www.boston.gov/departments/parks-and-recreation/urban-forest-plan

**Comment by subaha-cob** [comment]
@duffy-james this is another page with a different design on production.

**Comment by duffy-james** [comment]
@subaha-cob we'd definitely want to keep this design for production. It's used on a number of pages on the site.

Is that possible?

**Comment by subaha-cob** [comment]
@duffy-james Okay will do. It looks like it was added as content on the page which means it is not a component. Trying to figure out the best way to update all the pages using this design at once.

**Comment by duffy-james** [comment]
Yes, it's a CSS class added to the formatted text component after the fact. As long as we maintain the class in our CSS, we should be OK, right? If we're able to flag all of the pages using those classes, I can always come in after the fact and make sure they're updated.

It could also be a good reason to explore creating a "Timeline" component that has a similar look?
