### ISSUE TITLE
Featured Event Section

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#638]
Update Featured event node in Drupal template

Should look like this:
<img width="941" alt="Screen Shot 2021-11-05 at 10 38 19 AM" src="https://user-images.githubusercontent.com/57374913/140528140-f936cb83-d1aa-423b-adef-282ffa64197a.png">

Currently looks like this:
<img width="1524" alt="Screen Shot 2021-11-05 at 10 20 31 AM" src="https://user-images.githubusercontent.com/57374913/140527996-b01b1935-4b80-41f7-90f5-718c624903eb.png">

Page: https://www.boston.gov/departments/digital-team/test-page

**Comment by rachelsater** [comment]
@duffy-james Looks ok to me. The blue cta box is really close but it appears the same on production

**Comment by duffy-james** [comment]
@rachelsater looks fine to me. This is consistent with the "large" view now in our "events and notices" component.

**Comment by rachelsater** [comment]
thanks!
