### ISSUE TITLE
City Score Table and Timeline

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#639]
https://www.boston.gov/innovation-and-technology/cityscore

<img width="1226" alt="Screen Shot 2021-11-10 at 8 59 59 AM" src="https://user-images.githubusercontent.com/57374913/141127045-45a9134d-4c85-4aec-a5a4-35c22d8a096d.png">

Update styling for the table on City Score page.

**Comment by subaha-cob** [comment]
Update for test on UAT.
https://d8-uat.boston.gov/innovation-and-technology/cityscore

**Comment by subaha-cob** [comment]
@duffy-james  this is one of those pages with a new/different design on production.

**Comment by duffy-james** [comment]
@subaha-cob this is another page we'd need to address. If that's how it will look on production, it would lose the whole purpose for the page existing.

**Comment by subaha-cob** [comment]
@duffy-james So that means we should add the styling for that table back. We can do that.
