### ISSUE TITLE
Refactor user action component

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/patterns#67]
Refactor user action component

- [ ] Move to pattern library

- [ ] Create themeable

- [ ] Review backlog for bugs to resolve

**Comment by matthewcrist** [comment]
@reillyzlab Is this a Hub only component? Do you know of any pages that this currently exists on?

**Comment by reillyzlab** [comment]
Simply Hub and only on Hub homepage


[image: COB_B_Blue_square-01.png]

Reilly Zlab

Interim Chief Digital Officer, Digital Team <http://boston.gov/digital>

Department of Innovation & Technology

City of Boston | City Hall Room 703

617-635-0057 (w) | reilly.zlab@boston.gov


Keep up with the Digital Team Roadmap
<https://www.boston.gov/departments/digital-team/digital-team-roadmap>
Request <https://goo.gl/forms/rclxItfipgEEumml1> for us to work together
